# Generated by Django 4.0.4 on 2024-03-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrow_book_id_alter_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
