# Generated by Django 4.0.4 on 2024-03-13 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_book_inventory'),
        ('borrowing', '0003_alter_borrow_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL),
        ),
    ]
