# Generated by Django 4.0.4 on 2024-03-13 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrow_book_id_alter_borrow_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowing.borrow'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
