# Generated by Django 4.0.4 on 2024-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_url',
            new_name='session_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='session_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
